apiVersion: v1
kind: Secret
metadata:
  name: coder-db-creds
type: Opaque
stringData:
  postgres-password: {{ randAlphaNum 20 | quote }}
  username: coder
  password: {{ randAlphaNum 20 | quote }}
  database: coder
