apiVersion: v1
kind: Secret
metadata:
  name: coder-db-creds
type: Opaque
stringData:
  username: {{ randAlphaNum 8 | quote }}
  password: {{ randAlphaNum 20 | quote }}
  database: {{ randAlphaNum 10 | quote }}

