apiVersion: apps/v1
kind: Deployment
metadata:
  name: coder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coder
  template:
    metadata:
      labels:
        app: coder
    spec:
      containers:
        - name: coder
          image: "{{ .Values.coder.image.repository }}:{{ .Values.coder.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7080
          env:
            - name: CODER_PG_CONNECTION_URL
              value: >-
                postgres://{{ .Values.postgresql.auth.username | default (include "coder-full.username" .) }}:{{ .Values.postgresql.auth.password | default (include "coder-full.password" .) }}@{{ include "coder-full.postgresql.fullname" . }}:5432/{{ .Values.postgresql.auth.database | default (include "coder-full.database" .) }}?sslmode=disable
            {{- range .Values.coder.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.coder.resources | nindent 12 }}
