apiVersion: apps/v1
kind: Deployment
metadata:
  name: coder
  labels:
    app: coder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coder
  template:
    metadata:
      labels:
        app: coder
    spec:
      containers:
        - name: coder
          image: "{{ .Values.coder.image.repository }}:{{ .Values.coder.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7080
          env:
            - name: CODER_PG_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: coder-db-url
                  key: url
            {{- range .Values.coder.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.coder.resources | nindent 12 }}

