apiVersion: v1
kind: Secret
metadata:
  name: coder-db-url
  labels:
    app: coder
type: Opaque
stringData:
  url: >-
    postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "coder-full.postgresql.fullname" . }}:5432/{{ .Values.postgresql.auth.database }}?sslmode=disable

