apiVersion: v1
kind: Secret
metadata:
  name: coder-db-url
type: Opaque
stringData:
  url: >-
    postgres://coder:{{ (lookup "v1" "Secret" .Release.Namespace "coder-db-creds").data.password | b64dec }}@{{ include "coder-full.postgresql.fullname" . }}:5432/coder?sslmode=disable

