apiVersion: v1
kind: Secret
metadata:
  name: coder-db-creds
type: Opaque
data:
  username: {{ randAlphaNum 8 | b64enc | quote }}
  password: {{ randAlphaNum 20 | b64enc | quote }}
  database: {{ randAlphaNum 10 | b64enc | quote }}
