apiVersion: v1
kind: Service
metadata:
  name: coder
spec:
  selector:
    app: coder
  ports:
    - port: 80
      targetPort: 7080
      protocol: TCP
      name: http
  type: {{ .Values.coder.service.type }}
